### ISSUE TITLE
android.view.InflateException: Binary XML file line #44: Error inflating class Button

### ISSUE THREAD

**Issue by omegalogs4** [telegram-s/telegram#79]
when i click on "Start messaging" it it shows edit number dialog. from dialog when i click "Edit" it gives me error as "unfortunately telegram has stopped". please find log cat error as...

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.telegram.android.beta, PID: 9347
                  android.view.InflateException: Binary XML file line #44: Error inflating class Button
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:713)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492)
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
                      at org.telegram.android.fragments.AuthFragment.onCreateView(AuthFragment.java:94)
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927)
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467)
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440)
                      at android.os.Handler.handleCallback(Handler.java:733)
                      at android.os.Handler.dispatchMessage(Handler.java:95)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5001)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: android.content.res.Resources$NotFoundException: File res/drawable/st_btn_grey.xml from drawable resource ID #0x7f0200f0
                      at android.content.res.Resources.loadDrawable(Resources.java:2096)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:602)
                      at android.view.View.<init>(View.java:3554)
                      at android.widget.TextView.<init>(TextView.java:623)
                      at android.widget.Button.<init>(Button.java:107)
                      at android.widget.Button.<init>(Button.java:103)
                      at org.telegram.android.ui.FontController.loadButtonView(FontController.java:123)
                      at org.telegram.android.ui.FontController$ViewFactory.onCreateView(FontController.java:140)
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685)
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at org.telegram.android.fragments.AuthFragment.onCreateView(AuthFragment.java:94) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
                   Caused by: android.content.res.Resources$NotFoundException: Resource ID #0x7f0200f2
                      at android.content.res.Resources.getValue(Resources.java:1123)
                      at android.content.res.Resources.getDrawable(Resources.java:698)
                      at android.graphics.drawable.StateListDrawable.inflate(StateListDrawable.java:176)
                      at android.graphics.drawable.Drawable.createFromXmlInner(Drawable.java:937)
                      at android.graphics.drawable.Drawable.createFromXml(Drawable.java:877)
                      at android.content.res.Resources.loadDrawable(Resources.java:2092)
                      at android.content.res.TypedArray.getDrawable(TypedArray.java:602) 
                      at android.view.View.<init>(View.java:3554) 
                      at android.widget.TextView.<init>(TextView.java:623) 
                      at android.widget.Button.<init>(Button.java:107) 
                      at android.widget.Button.<init>(Button.java:103) 
                      at org.telegram.android.ui.FontController.loadButtonView(FontController.java:123) 
                      at org.telegram.android.ui.FontController$ViewFactory.onCreateView(FontController.java:140) 
                      at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:685) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:755) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.rInflate(LayoutInflater.java:758) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:492) 
                      at android.view.LayoutInflater.inflate(LayoutInflater.java:397) 
                      at org.telegram.android.fragments.AuthFragment.onCreateView(AuthFragment.java:94) 
                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1500) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:927) 
                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104) 
                      at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682) 
                      at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1467) 
                      at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:440) 
                      at android.os.Handler.handleCallback(Handler.java:733) 
                      at android.os.Handler.dispatchMessage(Handler.java:95) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method) 
I/GAV3: Thread[GAThread,5,main]: No campaign data found.
D/T|ContactsSync: User not logged in, delaying sync: contactsPreSync
I/Crashlytics: Crashlytics report upload complete: 592D6444007D-0001-2483-A9A3D71BB69D.cls
W/T|BackgroundSync: Sync failure: sendLog
W/T|BackgroundSync: java.lang.reflect.InvocationTargetException
                        at java.lang.reflect.Method.invokeNative(Native Method)
                        at java.lang.reflect.Method.invoke(Method.java:515)
                        at org.telegram.android.core.background.sync.BaseSync.performSync(BaseSync.java:180)
                        at org.telegram.android.core.background.sync.BaseSync$SyncHandler.handleMessage(BaseSync.java:265)
                        at android.os.Handler.dispatchMessage(Handler.java:102)
                        at android.os.Looper.loop(Looper.java:136)
                        at android.os.HandlerThread.run(HandlerThread.java:61)
                     Caused by: org.telegram.api.engine.TimeoutException
                        at org.telegram.api.engine.TelegramApi.doRpcCall(TelegramApi.java:369)
                        at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:428)
                        at org.telegram.api.engine.TelegramApi.doRpcCallNonAuth(TelegramApi.java:420)
                        at org.telegram.android.core.background.sync.BackgroundSync.sendLog(BackgroundSync.java:337)
                        at java.lang.reflect.Method.invokeNative(Native Method) 
                        at java.lang.reflect.Method.invoke(Method.java:515) 
                        at org.telegram.android.core.background.sync.BaseSync.performSync(BaseSync.java:180) 
                        at org.telegram.android.core.background.sync.BaseSync$SyncHandler.handleMessage(BaseSync.java:265) 
                        at android.os.Handler.dispatchMessage(Handler.java:102) 
                        at android.os.Looper.loop(Looper.java:136) 
                        at android.os.HandlerThread.run(HandlerThread.java:61) 

I checked all xml resources all are there in project drawable 
Please help me out...

**Comment by KuleshVandan** [comment]
solved?
